name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn test
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: gbyzzz/university_schedule_web_app:backend
        
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./db/Dockerfile
          context: ./db
          push: true
          tags: gbyzzz/university_schedule_web_app:postgres
      - name: Run Workflow
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'key.pem'
          fileDir: './'
          encodedString: ${{ secrets.KEY }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key_path: './key.pem'
          script: |
            docker login
            docker pull gbyzzz/university_schedule_web_app
            docker stop backend
            docker rm backend
            docker run --detach -name backend -p 443:8080 -e SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/university_web_app_db 
      - name: remove key
        run: rm key.pem
            
